# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed8bd127dc4384574973400d4df9ff8fcc16d173b220847fe02b15d49ae3867c8fd0f33c69ff8b6d22f379da480f9a31a256ec751fc3b0e0574b611427143bbf

test:
  secret_key_base: 4426aa8df051447c468148dcc0d7e92dbe1f73c8d64be2f45c5cec49bf07ecefd390ce0816ed71802b27e69ccb541498dc377f3081747f15eec3c8052cf30600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
